import Head from 'next/head'
import {useQuery} from 'urql'
import {PRODUCT_QUERY} from '../lib/query'

export default function Home() {
  // Fetch products from strapi
  const [results] = useQuery({query: PRODUCT_QUERY})
  consst {data, fetching, error} = results;
  // Check for the data coming in
  if(fetching) return <p>Loading...</p>;
  if(error) return <p>Oh no... {error.message}</p>
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello Next</h1>      
      </main>
    </div>
  )
}

